### PR TITLE
Fix expired deadlines in upcoming

### LINKED ISSUE #501: Upcoming deadlines show assignments that are past the deadline
**Describe the bug**
Upcoming deadlines includes assignments that are past the deadline 

**To Reproduce**
1. Make an assignment with a date before today
2. Go to the home page
3. See the assignment in the upcoming deadline

**Expected behavior**
Upcoming deadlines and no assignments that are already past the deadline

**Screenshots**
image

### PR DESCRIPTION
**Pull request by JowehL**
## Description
Expired deadlines no long show up in the deadline deck

## Summary of changes
- Fixes #501

### CODE REVIEW

**Comment by JowehL** [comment]
@Larspolo At the moment we can filter the expired deadlines in the backend in the serializer(which I don't recommend since we maybe want to use expired deadlines in other areas) or the assignment.py. And I don't think its clean to loop through all assignments again to check for expired deadlines.

Filtering the deadlines on the front-end would also be better for the server, maybe we could rename it to get_deadlines or create a separate serializer for it?

**Comment by Larspolo** [comment]
I would suggest using the following instead, this works a bit cleaner imo
image

**Comment by Larspolo** [comment]
http://localhost:8080/AssignmentsOverview should give all the assignments back, currently it only returns the upcoming.

**Comment by Larspolo** [comment]
Closing this PR because I made a lot more changes to this branch to fix deadline/assignment lists over all pages

**Pull request closed without merging**
