### PR TITLE
Actually test for coveralls

### PR DESCRIPTION
**Pull request by Rickyboy320**
Documentation implied it would work out of the box... guess I read it wrong.

Actually add the coveralls step in after_success, meanwhile I'll use this PR for some testing regarding coveralls...

### CODE REVIEW

**Comment by engelhamer** [comment]
Then why did he open this?

**Comment by Rickyboy320** [comment]
Because these are tests for travis / the pull request altogether, trying to get coveralls give some comments on this PR... seems to not work so far.

**Comment by libre-man** [comment]
You are sending the coverage of your javascript tests as those are executed after your python tests. I think if you reverse that it should work. However those to checks should be in different travis jobs. You could also simply remove the javascript tests as they are not really testing anything.

**Comment by Rickyboy320** [comment]
Seems to work now. Issue was actually that codecov and coveralls try to extract the xml in the toplevel dir. Instead I changed coverage to run from the toplevel dir. This way we are not necessarily limited to only backend.

**Comment by engelhamer** [comment]
> # [Codecov](https://codecov.io/gh/eJourn-al/eJournal/pull/405?src=pr&el=h1) Report
> > ❗️ No coverage uploaded for pull request base (`develop@79acc7a`). [Click here to learn what that means](https://docs.codecov.io/docs/error-reference#section-missing-base-commit).
> > The diff coverage is `n/a`.
> 
> [Impacted file tree graph](https://codecov.io/gh/eJourn-al/eJournal/pull/405?src=pr&el=tree)
> 
> ```diff
> @@            Coverage Diff             @@
> ##             develop     #405   +/-   ##
> ==========================================
>   Coverage           ?   52.17%           
> ==========================================
>   Files              ?       36           
>   Lines              ?     2854           
>   Branches           ?      452           
> ==========================================
>   Hits               ?     1489           
>   Misses             ?     1231           
>   Partials           ?      134
> ```
> 
> [Continue to review full report at Codecov](https://codecov.io/gh/eJourn-al/eJournal/pull/405?src=pr&el=continue).
> 
> > **Legend** - [Click here to learn more](https://docs.codecov.io/docs/codecov-delta)
> > `Δ = absolute <relative> (impact)`, `ø = not affected`, `? = missing data`
> > Powered by [Codecov](https://codecov.io/gh/eJourn-al/eJournal/pull/405?src=pr&el=footer). Last update [79acc7a...4403c13](https://codecov.io/gh/eJourn-al/eJournal/pull/405?src=pr&el=lastupdated). Read the [comment docs](https://docs.codecov.io/docs/pull-request-comments).

Judging by this marvelous result I guess we can proceed with merging? @Rickyboy320 @BigDGW

**Comment by Rickyboy320** [comment]
Yep! Should work for all PRs after merging.

**Pull request merged**
