### PR TITLE
Added the ability to apply multiple group filters to submissions

### LINKED ISSUE #731: Multi group filter for journals
A staff member should be able to filter journals based on multiple groups

### PR DESCRIPTION
**Pull request by mjvkeulen**
## Description
Staff members requested the ability to filter journals based on multiple groups

image

## Summary of changes
- Fixes #731

### CODE REVIEW

**Comment by engelhamer** [comment]
Now looks as follows:

image

**Comment by mjvkeulen** [comment]
The multi-select does not close on the initial button for the drop-down

**Comment by Larspolo** [comment]
FPS has 90+ groups. Search functionality would be appreciated. Also, active groups should be stated first to make it easier to remove them

**Comment by engelhamer** [comment]
- It is now possible to search:
Screenshot from 2019-10-18 18-29-57
- Values are sorted upon opening so selected values appear at the top of the list
- Mutation error has been resolved

**Comment by mjvkeulen** [comment]
Looking good!

I encountered this bug:
image

This seems to happen when you select a group filter for the first time.

**Comment by engelhamer** [comment]
Found that as well, the positioning restores itself upon closing the
selection or typing a search query.

> Looking good!
>
> I encountered this bug:
> [image: image]
> <https://user-images.githubusercontent.com/39912610/67113430-c8c40e80-f1d9-11e9-8f5b-f59f4c36d7eb.png>
>
> This seems to happen when you select a group filter for the first time.
>

**Pull request merged**
